# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.manager.post:
        class: AppBundle\Manager\PostManager
        arguments:
            # dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: AppBundle\Entity\Post
