stof_doctrine_extensions:
    default_locale: en_US
    uploadable:
        validate_writable_directory: false
    orm:
        default:
            timestampable: true
            softdeleteable: true
            sluggable: true
